[package]
name = "gsplat-hierarchy"
version = "0.1.3"
description = "Offline-authored replacement hierarchy primitives for gsplat-rs."
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
gsplat-io-ply = { path = "../gsplat-io-ply", version = "0.1.3" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
